default: # see available parameters with command : app/console debug:container --parameters | grep sonata.admin
    sonata_block.blocks:
        default:
            sonata.admin.block.admin_list:
                contexts: ["admin"]
                cache: ~
                settings: []
        replace:
            sonata.admin.block.admin_list:
                contexts: ["cms","admin"]
                cache: ~
                settings: []
            sonata.user.block.menu:
                contexts: ["cms","admin"]
                cache: ~
                settings: []
            sonata.user.block.account:
                contexts: ["cms","admin"]
                cache: ~
                settings: []
            sonata.block.service.text:
                contexts: ["cms","admin"]
                cache: ~
                settings: []
    sonata.admin.configuration.templates:
        default:
            layout: SonataAdminBundle::standard_layout.html.twig
            user_block: SonataUserBundle:Admin/Core:user_block.html.twig
        replace:
            layout: LibrinfoDecoratorBundle:Admin:layout.html.twig
            user_block: LibrinfoDecoratorBundle:Admin/Block:user_block.html.twig