parameters:
    librinfo:
        configuration:
            templates:
                show:
                    email: LibrinfoCoreBundle:CRUD:list_field_email.html.twig
                list:
                    email: LibrinfoCoreBundle:CRUD:list_field_email.html.twig
