services:
    librinfo_core.twig.base_extension:
        class: Librinfo\CoreBundle\Twig\Extensions\BaseExtension
        tags: [{ name: twig.extension }]
        calls:
            - [setRouter,[@router]]

    librinfo_core.services.authenticate:
        class: Librinfo\CoreBundle\Services\Authenticate
        arguments: [@security.token_storage]
        calls:
            - [setUserManager, ['@fos_user.user_manager']]

    sonata.admin.manager.orm:
        class: Librinfo\CoreBundle\Model\ModelManager
        arguments: [@doctrine]

    sonata.admin.exporter:
        class: Librinfo\CoreBundle\Admin\Exporter
        calls:
            - [setRouter, ['@router']]
